---
name: Pod-PseudoPod-LaTeX
version: 1.000
author:
  - 'chromatic <chromatic@wgz.org>'
abstract: convert Pod::PseudoPod documents into LaTeX
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  IO::String: 0
  Test::More: 0.60
requires:
  Pod::PseudoPod: 0.15
  perl: v5.6.2
configure_requires:
  Module::Build: 0.34
provides:
  Pod::PseudoPod::LaTeX:
    file: lib/Pod/PseudoPod/LaTeX.pm
    version: 1.000
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
